package CorbaBanque;


/**
* CorbaBanque/IBanqueRemoteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banque.idl
* lundi 10 novembre 2025 16 h 52 WAT
*/

public interface IBanqueRemoteOperations 
{
  void creerCompte (CorbaBanque.Compte cpte);
  void verser (float mt, int code);
  void retirer (float mt, int code);
  CorbaBanque.Compte getCompte (int code);
  CorbaBanque.Compte[] getComptes ();
  double conversion (float mt);
} // interface IBanqueRemoteOperations
