package CorbaBanque;

/**
* CorbaBanque/IBanqueRemoteHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banque.idl
* lundi 10 novembre 2025 16 h 52 WAT
*/

public final class IBanqueRemoteHolder implements org.omg.CORBA.portable.Streamable
{
  public CorbaBanque.IBanqueRemote value = null;

  public IBanqueRemoteHolder ()
  {
  }

  public IBanqueRemoteHolder (CorbaBanque.IBanqueRemote initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CorbaBanque.IBanqueRemoteHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CorbaBanque.IBanqueRemoteHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CorbaBanque.IBanqueRemoteHelper.type ();
  }

}
