package CorbaBanque;


/**
* CorbaBanque/tabComptesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banque.idl
* lundi 10 novembre 2025 16 h 52 WAT
*/

public final class tabComptesHolder implements org.omg.CORBA.portable.Streamable
{
  public CorbaBanque.Compte value[] = null;

  public tabComptesHolder ()
  {
  }

  public tabComptesHolder (CorbaBanque.Compte[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CorbaBanque.tabComptesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CorbaBanque.tabComptesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CorbaBanque.tabComptesHelper.type ();
  }

}
